# -*- coding: utf-8 -*-
"""Código

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r0ZRb7Fje6l4S6uI40C6LFlwSHqoTxl-
"""

# Bienvenida al usuario
def principal():
  return ("¿Listo para aprender sobre el desarrollo de fármacos?")

# Insertar imagen auxiliar
from IPython.display import Image
from IPython.core.display import HTML 
Image(url= "https://www.researchgate.net/publication/343786548/figure/fig3/AS:926849605591040@1597989574016/The-autoencoder-and-the-variational-autoencoder-a-An-autoencoder-encodes-input_W640.jpg", width=650)

"""# Bienvenidos
Aquí comienza todo
# ***Hola***
"""

# Welcome to python:
name = input("Introduce name:")
print(f"Say hello, {name}!")